# A sample Gemfile

source "https://rubygems.org"
ruby "2.1.5"
group :development do
  gem 'vagrant', github: 'https://github.com/Grace-Andrews/custom-vagrant.git'
end

# group :plugins do
#  gem "vagrant-configs", path: "."
# end
# gem "rails"
